# Generated by Django 2.2.10 on 2020-03-05 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0002_auto_20200229_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hired_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
